name: Test updater action
on:
  push:
  workflow_dispatch:

jobs:
  check-for-updates:
    name: Check for updates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - file: test-files/alpine-Containerfile
            osVersion: 3.18
            architectures: "x86_64, aarch64, armhf, armv7, x86"
          - file: test-files/debian-Containerfile
            osVersion: bookworm
            architectures: "amd64, arm64, i386, armel, armhf"
      fail-fast: false
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v4

      - name: 🚀 Run Updater
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          containerFile: ${{ matrix.test.file }}
          osVersion: ${{ matrix.test.osVersion }}
          architectures: ${{ matrix.test.architectures }}
          dryRun: true
